model:
  debug:
    anomaly-detection: False
  wandb:
    enabled: True
  dask:
    enabled: True
    tempdir: /data/malexe/scratch/GNN-WEATHER/dask
    trim-worker-memory: True
    num-workers: 8
    threads-per-worker: 2
